# @package _global_

# Fixed constants of the dataset
name: Cora
task: node_classification
num_node_features: 1433
output_dim: 7


#training parameters
num_epochs: 300
weight_decay: 0.005
split: 0
activation: 'leaky_relu'
gradient_clipping: False

#model parameters
normalize: True
self_loops: False
hidden_dim: 32
hidden_gcn_dim: 0
dropout_rate: 0.2
L: 2
N: 200
h: 0.02

initial_processing: False

#lr scheduler parameters
reduce_on_plateau: True
lr: 0.001
lr_patience: 10
lr_factor: 0.5
min_lr: 0.0001

#loss function and metrics
loss_fn: 'cross_entropy'