# @package _global_

# Fixed constants of the dataset
name: Peptides-struct
task: graph_regression
num_node_features: 9
output_dim: 11


#training parameters
num_epochs: 300
batch_size: 64
weight_decay: 0.0
lr: 0.002
split: 0
activation: 'gelu'
gradient_clipping: False

#model parameters
normalize: True
self_loops: False
hidden_dim: 128
hidden_gcn_dim: 0
dropout_rate: 0
L: 3
N: 20
h: 0.5

initial_processing: True


#loss function and metrics
loss_fn: 'l1'