# @package _global_

# Fixed constants of the dataset
name: Peptides-struct
task: graph_regression
num_node_features: 9
output_dim: 11


#training parameters
num_epochs: 300
batch_size: 64
weight_decay: 1e-3
lr: 0.001
split: 0
activation: 'relu'
gradient_clipping: False

#model parameters
normalize: True
self_loops: False
hidden_dim: 256
hidden_gcn_dim: 0
dropout_rate: 0
L: 3
N: 150
h: 0.03

initial_processing: False


#loss function and metrics
loss_fn: 'l1'