# @package _global_

# Fixed constants of the dataset
name: wisconsin
task: node_classification
num_node_features: 1703
output_dim: 5


#training paraeters
num_epochs: 300
weight_decay: 0.001
split: 0
activation: 'leaky_relu'
gradient_clipping: False

#model parameters
normalize: True
self_loops: False
hidden_dim: 32
hidden_gcn_dim: 0
dropout_rate: 0.3
L: 1
N: 4
h: 0.2

initial_processing: False

#lr scheduler parameters
reduce_on_plateau: True
lr: 0.01
lr_patience: 10
lr_factor: 0.5
min_lr: 0.0001

#loss function and metrics
loss_fn: 'cross_entropy'