# @package _global_

# Fixed constants of the dataset
name: zinc
task: graph_regression
num_node_features: 1
output_dim: 1

#training parameters
num_epochs: 100
weight_decay: 0
lr: 0.0005
split: 0
activation: 'leaky_relu'
batch_size: 64
gradient_clipping: False
reduce_on_plateau: False

#model parameters
normalize: True
self_loops: True
hidden_dim: 512
n_head: 8
num_layers: 3
hidden_gcn_dim: 0
dropout_rate: 0.0
L: 3
N: 100
h: 0.05
initial_processing: True

#loss function and metrics
loss_fn: 'l1'
