# @package _global_

# Fixed constants of the dataset
name: PubMed
task: node_classification
num_node_features: 500
output_dim: 3


#training parameters
num_epochs: 300
weight_decay: 0.005
split: 0
activation: 'leaky_relu'
gradient_clipping: False

#model parameters
normalize: False
self_loops: False
hidden_dim: 24
hidden_gcn_dim: 0
dropout_rate: 0.3
L: 1
N: 50
h: 0.06

initial_processing: False

#lr scheduler parameters
reduce_on_plateau: True
lr: 0.0025
lr_patience: 10
lr_factor: 0.5
min_lr: 0.0001

#loss function and metrics
loss_fn: 'cross_entropy'